GOTO 555 WHERE NOT EXISTS(
SELECT 'X'
FROM CUSTOMCONST
WHERE NAME = 'ZTAN_EMAILCIV'
AND   VALUE = 1.0) ;
GOTO 555 WHERE :$.FFF = '' ;
/**/
/*
EXECUTE DELWINDOW 'f', :$.FFF ;
*/
/**/
LABEL 555 ;
GOTO 9988 WHERE SQL.ENV NOT IN ('parkas','fc','parktes','conmart') ; 
/******/
LINK INVOICES TO :$.PAR ; 
ERRMSG 1 WHERE :RETVAL <= 0 ; 
/*****/
:ZYUV_IV = 0 ; 
SELECT IV INTO :ZYUV_IV FROM INVOICES WHERE IV <>0 ; 
/****/
UNLINK INVOICES ; 
:ZYUV_CUST = 0 ; 
:ZYUV_ACCOUNT  = 0 ; 
:ZYUV_IVNUM = ''; 
/*******/
SELECT
INVOICES.IVNUM,
INVOICES.CUST,
INVOICES.ACCOUNT
INTO :ZYUV_IVNUM,:ZYUV_CUST,:ZYUV_ACCOUNT
FROM INVOICES 
WHERE IV = :ZYUV_IV ; 
/******/
:ZYUV_CUSTACCOUNT = 0 ; 
SELECT
CUSTOMERS.CUST
INTO :ZYUV_CUSTACCOUNT
FROM CUSTOMERS
WHERE CUSTOMERS.ACCOUNT = :ZYUV_ACCOUNT
AND :ZYUV_ACCOUNT <>0 ; 
/*****/
:ZYUV_FINALCUST = 0 ; 
:ZYUV_FINALCUST = (:ZYUV_CUSTACCOUNT <> 0 ? 
:ZYUV_CUSTACCOUNT : :ZYUV_CUST) ; 
/*****/
:ZYUV_FILENAME = '' ;
:ZYUV_FILENAME = STRCAT('..\..\system\mail\INVOICE','-',
:ZYUV_IVNUM,'-',SQL.ENV,
'.pdf');
/*****/
INSERT INTO ZTAN_IVPRINTORIG(USER, IV)
VALUES(SQL.USER, :ZYUV_IV) ;
/*****/
EXECUTE WINHTML '-d', 'ZTAN_EWWWSHOWCIV', '', '', '-v', :ZYUV_IV, '-s', 
'-edoc', '-pdf', :ZYUV_FILENAME,'-format',-12; 
/*
XECUTE WINHTML '-d', 'ZTAN_EWWWSHOWCIV', '', '', '-v', :ZYUV_IV, '-s', 
'-signpdf', '-pdf', :ZYUV_FILENAME,'-format',-12; 
*/
/*****/
:ZYUV_ORDMAIL = '' ;
SELECT SQL.TMPFILE INTO :ZYUV_ORDMAIL FROM DUMMY ;
LINK GENERALLOAD TO :ZYUV_ORDMAIL ;
/*** CREATE EMAIL FORMAT **/
:TITLE = '' ;
SELECT COMPDESA INTO :TITLE
FROM ENVIRONMENT
WHERE DNAME = SQL.ENV ;
:ZYUV_SUBJECT = '' ;
:ZYUV_SUBJECT = STRCAT( 'Attached Final Invoice From ' ,:TITLE) ;
:LINE = 0 ;
SELECT LINE INTO :LINE FROM GENERALLOAD ORDER BY 1 DESC ;
INSERT INTO GENERALLOAD(LINE,RECORDTYPE,TEXT1,ZCRE_TEXT1)
VALUES (:LINE + 1,'1',:ZYUV_SUBJECT,:ZYUV_FILENAME);
/**/
:LINE2 = 0 ;
SELECT LINE INTO :LINE2 FROM GENERALLOAD ORDER BY 1 DESC ;
INSERT INTO GENERALLOAD (LINE,RECORDTYPE,TEXT2,CHAR1)
SELECT
SQL.LINE + :LINE2,
'3',
PHONEBOOK.EMAIL,
'T'
FROM PHONEBOOK
WHERE PHONEBOOK.CUST = :ZYUV_FINALCUST
AND PHONEBOOK.ZRON_INVOICE = 'Y' ;
EXECUTE INTERFACE 'ZYUV_OPENPRDMAIL',SQL.TMPFILE,'-L',:ZYUV_ORDMAIL;
/**/
:KEY1 = '' ;
SELECT
GENERALLOAD.KEY1
INTO :KEY1
FROM GENERALLOAD
WHERE RECORDTYPE = '1'
AND LOADED = 'Y' ;
:ZYUV_ORDSEND = '' ;
SELECT SQL.TMPFILE INTO :ZYUV_ORDSEND FROM DUMMY ;
LINK MAILBOX TO :ZYUV_ORDSEND ;
GOTO 9988 WHERE :RETVAL <= 0 ;
INSERT INTO MAILBOX
SELECT * FROM MAILBOX ORIG
WHERE ITOA(ORIG.MAILBOX) = :KEY1 ;
EXECUTE SENDMAIL :ZYUV_ORDSEND,SQL.TMPFILE ;
UNLINK MAILBOX ;
UNLINK GENERALLOAD ;
/**/
LABEL 9988 ;


