DECLARE C CURSOR FOR
SELECT
COSTCENTERS.COSTC,
COSTCENTERS.COSTCNAME
FROM COSTCENTERS
WHERE EXISTS(
SELECT
'X'
FROM ZARI_CONTTRACK,ZTAN_CONTTRACKTYPE
WHERE ZARI_CONTTRACK.COSTC = COSTCENTERS.COSTC
AND ZARI_CONTTRACK.CONTTRACKTYPE = ZTAN_CONTTRACKTYPE.CONTTRACKTYPE
AND ZTAN_CONTTRACKTYPE.TYPECODE = 'LDF')
AND NOT EXISTS(
SELECT
'X'
FROM ZARI_CONTTRACK,ZTAN_CONTTRACKTYPE
WHERE ZARI_CONTTRACK.COSTC = COSTCENTERS.COSTC
AND ZARI_CONTTRACK.CONTTRACKTYPE = ZTAN_CONTTRACKTYPE.CONTTRACKTYPE
AND ZTAN_CONTTRACKTYPE.TYPECODE = 'CLS')  
 ; 
OPEN C ;
GOTO 90 WHERE :RETVAL <= 0 ; 
LABEL 10 ;
:COSTC = 0 ; 
:COSTCNAME = ''; 
FETCH C INTO :COSTC,:COSTCNAME ; 
GOTO 80 WHERE :RETVAL <= 0 ; 
:KLINE  = 0 ; 
/********/
:FROMDATE = :ZYUV_FROMDATE = 01/01/88 ; 
SELECT
FROMDATE,
ZYUV_FROMDATE
INTO :FROMDATE,:ZYUV_FROMDATE
FROM ZARI_CONTTRACK
WHERE COSTC = :COSTC 
ORDER BY 2 DESC ; 
SELECT MAX(KLINE) INTO :KLINE FROM ZARI_CONTTRACK  ; 
INSERT INTO ZARI_CONTTRACK (COSTC,KLINE,FROMDATE,ZYUV_FROMDATE,CONTTRACKTYPE)
VALUES (:COSTC,:KLINE,:FROMDATE,:ZYUV_FROMDATE + 1, 19) ; 
LOOP 10 ; 
LABEL 80 ; 
CLOSE C ; 
LABEL 90 ; 
