LINK GENERALLOAD TO :$.GEN ;
ERRMSG 1 WHERE :RETVAL <=0 ;
/*** LOOP OVER COSTCENTERS THAT HAVE BEEN INVOICES AND FLAG AS CLOSE
***/
DECLARE ZYUV_CLOSE CURSOR FOR
SELECT
COSTCENTERS.COSTC
FROM COSTCENTERS
WHERE EXISTS(
SELECT
'X'
FROM INVOICES,INVOICEITEMS,GENERALLOAD
WHERE INVOICES.IV = INVOICEITEMS.IV
AND INVOICEITEMS.COSTC = COSTCENTERS.COSTC
AND INVOICES.IV = ATOI(GENERALLOAD.KEY1)
AND GENERALLOAD.LOADED = 'Y'
AND GENERALLOAD.RECORDTYPE = '1'
) ;
/******/
OPEN ZYUV_CLOSE ;
GOTO 90 WHERE :RETVAL <= 0 ;
LABEL 10 ;
:COSTC = 0;
FETCH ZYUV_CLOSE INTO :COSTC ;
GOTO 80 WHERE :RETVAL <= 0 ;
UPDATE COSTCENTERS SET ZTAN_CONTCLOESD = 'Y'
WHERE COSTC = :COSTC ;
LOOP 10 ;
LABEL 80 ;
CLOSE ZYUV_CLOSE ;
LABEL 90 ;
