LINK GENERALLOAD TO :$.GEN ;
GOTO 9988 WHERE :RETVAL <= 0 ;
/***************/
DECLARE DEM CURSOR FOR
SELECT
COSTCENTERS.COSTC,
COSTCENTERS.COSTCNAME,
CONTAINERTYPES.CONTAINERTYPE
FROM COSTCENTERS,CONTAINERTYPES
WHERE COSTCENTERS.ZTAN_CONTCLOESD <> 'Y'
AND CONTAINERTYPES.CONTAINERTYPE = COSTCENTERS.ZYUV_CONTTYPE
AND EXISTS(
SELECT
'X'
FROM ZARI_CONTTRACK,ZTAN_CONTTRACKTYPE
WHERE ZTAN_CONTTRACKTYPE.CONTTRACKTYPE =
ZARI_CONTTRACK.CONTTRACKTYPE
AND ZTAN_CONTTRACKTYPE.RE = 'Y'
AND ZARI_CONTTRACK.COSTC = COSTCENTERS.COSTC
)
AND COSTCENTERS.COSTCNAME = '44307';
OPEN DEM ;
GOTO 90 WHERE :RETVAL <= 0 ;
LABEL 10 ;
:COSTC = 0 ;
:COSTCNAME = '';
:CONTAINERTYPE = 0 ;
FETCH DEM INTO :COSTC,:COSTCNAME,:CONTAINERTYPE ;
GOTO 80 WHERE :RETVAL <=0  ;
/******/
/**** FIRST STEP CALC RETURN***/
:ZYUV_REDATE = 01/01/88 ;
SELECT
ZARI_CONTTRACK.FROMDATE
INTO :ZYUV_REDATE
FROM ZARI_CONTTRACK,ZTAN_CONTTRACKTYPE
WHERE ZARI_CONTTRACK.COSTC = :COSTC
AND ZARI_CONTTRACK.CONTTRACKTYPE = ZTAN_CONTTRACKTYPE.CONTTRACKTYPE
AND ZTAN_CONTTRACKTYPE.RE = 'Y'
ORDER BY 1 ASC ;
/**** FIRST STEP START RETURN***/
:ZYUV_DFDATE = 01/01/88 ;
SELECT
ZARI_CONTTRACK.FROMDATE
INTO :ZYUV_DFDATE
FROM ZARI_CONTTRACK,ZTAN_CONTTRACKTYPE
WHERE ZARI_CONTTRACK.COSTC = :COSTC
AND ZARI_CONTTRACK.CONTTRACKTYPE = ZTAN_CONTTRACKTYPE.CONTTRACKTYPE
AND ZTAN_CONTTRACKTYPE.DF = 'Y'
ORDER BY 1 ASC ;
/********* CALC TOTAL DAYS***/
:ZYUV_DEMDAYS = 0 ;
:ZYUV_DEMDAYS = 1 +  ((:ZYUV_REDATE - :ZYUV_DFDATE)/24:00);
/***** CALC FREE DAYS***/
/*** FIRST GENERAL TARIFF*/
:ZYUV_FREE = 0 ;
:ZYUV_RATE = 0.00 ;
SELECT
ZYUV_DEMTARIF.FREE_DAYS,
ZYUV_DEMTARIF.RATE
INTO :ZYUV_FREE,:ZYUV_RATE
FROM ZYUV_DEMTARIF
WHERE ZYUV_DEMTARIF.CONTAINERTYPE = :CONTAINERTYPE ;
/*** SECOND ORDER TARIFF*/
:ZYUV_ORD = 0;
SELECT
ORDERS.ORD
INTO :ZYUV_ORD
FROM ORDERS,SPLITCOSTCENTERS,COSTCENTERS
WHERE ORDERS.ORD = SPLITCOSTCENTERS.IV
AND SPLITCOSTCENTERS.TYPE = 'O'
AND SPLITCOSTCENTERS.KLINE = -1
AND COSTCENTERS.COSTC = SPLITCOSTCENTERS.COSTC
AND COSTCENTERS.COSTC = :COSTC ;
/*****/
:ZYUV_ORDFREE = 0 ;
SELECT
NIRW_ZTANFREEDAYS
INTO :ZYUV_ORDFREE
FROM ORDERS
WHERE ORD = :ZYUV_ORD ;
/**** CALC THE FINAL FREE DAYS **/
:ZYUV_FINALFREE = 0 ;
:ZYUV_FINALFREE = (:ZYUV_ORDFREE <> 0 ?
:ZYUV_ORDFREE : :ZYUV_FREE) ;
/*DAYS TO BE BILLED */
:ZYUV_BILLED = 0 ;
:ZYUV_BILLED = MAXOP(:ZYUV_DEMDAYS - :ZYUV_FINALFREE,0) ;
/*********/
GOTO 900 WHERE :ZYUV_BILLED = 0 ;
/*** CALC THE CUSTOMER-THE CUSTOM BROKER FROM THE ORDER ****/
:ZYUV_CUST = 0 ;
:ZYUV_CUSTNAME = '';
SELECT
CUSTOMERS.CUST,
CUSTOMERS.CUSTNAME
INTO :ZYUV_CUST,:ZYUV_CUSTNAME
FROM CUSTOMERS ?,ORDERS
WHERE CUSTOMERS.CUST = ORDERS.ZTAN_CUSTOMSCUST
AND ORDERS.ORD = :ZYUV_ORD ;
/**** OPEN THE INVOICE ***/
:LINE = 0 ;
SELECT
MAX(LINE) INTO :LINE
FROM GENERALLOAD ;
INSERT INTO GENERALLOAD (LINE,RECORDTYPE,TEXT1)
VALUES (:LINE + 1,'1',:ZYUV_CUSTNAME) ;
/*** GET THE PART**/
:ZYUV_PART = 0 ;
SELECT
PART INTO :ZYUV_PART
FROM PART
WHERE PARTNAME = 'DEM' ;
/*** SET THE CURR*/
:ZYUV_CODE = '';
SELECT
CODE INTO :ZYUV_CODE
FROM CURRENCIES
WHERE CURRENCY = -2 ;
/***********/
:LINE = 0 ;
SELECT
MAX(LINE) INTO :LINE
FROM GENERALLOAD ;
INSERT INTO GENERALLOAD (LINE,RECORDTYPE,INT1,TEXT1,INT3,INT4,
REAL1,INT5,INT6,REAL2/*,INT8,INT9*/)
VALUES (:LINE + 1, '2',:ZYUV_PART,:ZYUV_CODE,:COSTC,
INTQUANT(:ZYUV_BILLED + 0.00),
:ZYUV_RATE,:ZYUV_DEMDAYS,:ZYUV_FINALFREE,:ZYUV_BILLED/*,
:ZYUV_DFDATE,:ZYUV_REDATE*/) ;
/**** GET THE HANDLING COMISSION**/
:LINE = 0 ;
SELECT
MAX(LINE) INTO :LINE
FROM GENERALLOAD ;
INSERT INTO GENERALLOAD (LINE,RECORDTYPE,INT1,TEXT1,INT4,REAL1)
SELECT
SQL.LINE + :LINE,
'2',
PART.PART,
:ZYUV_CODE,
INTQUANT(1.0),
SPARTPRICE.PRICE
FROM PART,SPARTPRICE,SUPPRICELIST
WHERE SUPPRICELIST.SUPPLIST = SPARTPRICE.SUPPLIST
AND SPARTPRICE.PART = PART.PART
AND SUPPRICELIST.SUPPLIST = 13 ;
/*********/
LABEL 900 ;
LOOP 10 ;
LABEL 80 ;
CLOSE DEM ;
LABEL 90 ;
/*****/
EXECUTE INTERFACE 'ZTAN_CONTDELAYCIV',SQL.TMPFILE,'-L',:$.GEN ;
DELETE FROM GENERALLOAD ORIG ;
INSERT INTO GENERALLOAD ORIG
SELECT * FROM GENERALLOAD ;
UNLINK GENERALLOAD ;
LABEL 9988 ;
/******/
