:ZYUV_IV = 0 ; 
SELECT IV INTO :ZYUV_IV FROM INVOICES WHERE IVNUM = 'SI236ARK006766' ; 
UPDATE INVOICES SET PRINTED = '' WHERE IV = :ZYUV_IV ; 
:ZYUV_CUST = 0 ; 
:ZYUV_IVNUM = ''; 
SELECT
INVOICES.CUST,
INVOICES.IVNUM
INTO :ZYUV_CUST,:ZYUV_IVNUM
FROM INVOICES
WHERE IV = :ZYUV_IV ; 
/***/
:ZYUV_ACCOUNT = 0 ; 
SELECT 
INVOICES.ACCOUNT
INTO :ZYUV_ACCOUNT
FROM INVOICES
WHERE IV = :ZYUV_IV ; 
SELECT :ZYUV_CUST,:ZYUV_ACCOUNT FROM DUMMY FORMAT;
:ZYUV_CUSTACCOUNT = 0 ;
SELECT
CUSTOMERS.CUST
INTO :ZYUV_CUSTACCOUNT
FROM CUSTOMERS
WHERE CUSTOMERS.ACCOUNT = :ZYUV_ACCOUN
AND :ZYUV_ACCOUNT <>0  ; 
/****/
SELECT :ZYUV_CUSTACCOUNT FROM DUMMY FORMAT;
/***/
:ZYUV_FINALCUST = 0 ; 
:ZYUV_FINALCUST = (:ZYUV_CUSTACCOUNT <> 0 ? 
:ZYUV_CUSTACCOUNT : :ZYUV_CUST) ; 
/****/
SELECT :ZYUV_FINALCUST FROM DUMMY FORMAT;
/****/
:ZYUV_FILENAME = '' ;
:ZYUV_FILENAME = STRCAT('..\..\system\mail\INVOICE','-',
:ZYUV_IVNUM,'-',SQL.ENV,
'.pdf');
/*:OUT = '..\..\system\mail/alert.pdf';*/
EXECUTE WINHTML '-d', 'ZTAN_EWWWSHOWCIV', '', '', '-v', :ZYUV_IV, '-s', 
'-edoc', '-pdf', :ZYUV_FILENAME,'-format',-12; 







