GOTO 9988 WHERE SQL.ENV <> 'parkas' ;
GOTO 9988 WHERE :$$.EXTTYPE <> 'O' ;
:ZYUV_GEN = '';
SELECT SQL.TMPFILE INTO :ZYUV_GEN FROM DUMMY ;
LINK GENERALLOAD TO :ZYUV_GEN ;
GOTO 9988 WHERE :RETVAL <= 0 ;
/**/
:ORD = :CUST = 0 ;
:ORDNAME = :CUSTNAME = :LOADPORT = :DESTPORT = '' ;
:LOADPORTID = :DESTPORTID = 0 ;
:LOADDATE = 01/01/88 ;
:INCOTERMS = '';
:ORDTYPE = '';
SELECT
ORDERS.ORD,
ORDERS.ORDNAME,
CUSTOMERS.CUST,
CUSTOMERS.CUSTNAME,
PORTS.PORTNAME,
PORTS1.PORTNAME,
PORTS.PORT,
PORTS1.PORT,
ORDERS.ZTAN_LOADDATE,
IMPTERMS.IMPTERMNAME,
ZYUV_ORDTYPE.ZYUV_ORDCODE
INTO
:ORD,:ORDNAME,:CUST,:CUSTNAME,:LOADPORT,:DESTPORT,
:DESTPORTID,:LOADPORTID,:LOADDATE,:INCOTERMS,:ORDTYPE
FROM ORDERS,PORTS,PORTS PORTS1,CUSTOMERS,IMPTERMS,ZYUV_ORDTYPE
WHERE ORDERS.CUST = CUSTOMERS.CUST
AND ORDERS.ZTAN_PORT = PORTS.PORT
AND ZYUV_ORDTYPE.ZYUV_ORDTYPE = ORDERS.ZYUV_ORDTYPE
AND IMPTERMS.IMPTERM = ORDERS.ZTAN_IMPTERM
AND ORDERS.ZTAN_TOPORT = PORTS1.PORT
AND ORDERS.ORD = :$$.ORD ;
/**************************************************/
/***** COUNTS CONTS FOR LOCAL***/
:ZYUV_CONTCOUNT = 0 ;
SELECT
COUNT(*)
INTO :ZYUV_CONTCOUNT
FROM ORDERS,SPLITCOSTCENTERS,COSTCENTERS,CONTAINERTYPES
WHERE ORDERS.ORD = :ORD
AND ORDERS.ORD = SPLITCOSTCENTERS.IV
AND SPLITCOSTCENTERS.TYPE = 'O'
AND SPLITCOSTCENTERS.KLINE = -1
AND SPLITCOSTCENTERS.COSTC = COSTCENTERS.COSTC
AND CONTAINERTYPES.CONTAINERTYPE = COSTCENTERS.ZYUV_CONTTYPE
AND COSTCENTERS.COSTC <>0 ;
/***/
:LINE = 0 ;
SELECT MAX(LINE) INTO :LINE FROM GENERALLOAD ;
INSERT INTO GENERALLOAD (LINE,RECORDTYPE,INT1,TEXT1)
VALUES (:LINE + 1, '1', :ORD,:ORDNAME) ;
/****************************************/
DECLARE @ZYUV_TARRIF CURSOR FOR
SELECT DISTINCT
ORDERITEMS.ORDI,
CONTAINERTYPES.CONTAINERTYPE,
CONTAINERTYPES.CONTTYPECODE,
PART.PART,
PART.PARTNAME
FROM
PART,ORDERITEMS,ORDERS,CONTAINERTYPES,SPLITCOSTCENTERS,COSTCENTERS,
ZRON_ORDERTERMS
WHERE ORDERS.ORD = ORDERITEMS.ORD
AND SPLITCOSTCENTERS.IV = ORDERS.ORD
AND SPLITCOSTCENTERS.COSTC = COSTCENTERS.COSTC
AND SPLITCOSTCENTERS.TYPE = 'O'
AND SPLITCOSTCENTERS.KLINE = -1
AND COSTCENTERS.ZYUV_CONTTYPE = CONTAINERTYPES.CONTAINERTYPE
AND PART.PART = ORDERITEMS.PART
AND ORDERS.ORD = :ORD
AND ZRON_ORDERTERMS.ORDETERM = ORDERITEMS.ZRON_ORDETERM
AND ZRON_ORDERTERMS.ORDTERMCODE = '002'  ;
/******************************************************************/
OPEN @ZYUV_TARRIF ;
GOTO 90 WHERE :RETVAL <= 0 ;
LABEL 10 ;
:PART = :ORDI = :CONTYPE  = 0 ;
:PARTNAME = :CONTCODE = '';
FETCH @ZYUV_TARRIF INTO :ORDI,:CONTYPE,:CONTCODE,:PART,:PARTNAME ;
GOTO 80 WHERE :RETVAL <= 0 ;
:SURPRICE = :SPCPRICE = :GENPRICE = 0.00 ;
/***** COUNT CONTAINERTYPE IN ORDER**/
:CONTCOUNT = 0 ;
SELECT
COUNT(*)
INTO :CONTCOUNT
FROM ORDERS,SPLITCOSTCENTERS,COSTCENTERS,CONTAINERTYPES
WHERE ORDERS.ORD = :ORD
AND ORDERS.ORD = SPLITCOSTCENTERS.IV
AND SPLITCOSTCENTERS.TYPE = 'O'
AND SPLITCOSTCENTERS.KLINE = -1
AND SPLITCOSTCENTERS.COSTC = COSTCENTERS.COSTC
AND CONTAINERTYPES.CONTAINERTYPE = COSTCENTERS.ZYUV_CONTTYPE
AND COSTCENTERS.COSTC <>0
AND CONTAINERTYPES.CONTAINERTYPE= :CONTYPE ;
/*********** CHECK FOR TEU FLAG****/
:TEU_FLAG = 'N' ;
SELECT
SPARTPRICE.ZYUV_TEU
INTO :TEU_FLAG
FROM SPARTPRICE
WHERE SPARTPRICE.PART = :PART ;
:TEU = 0 ;
/**/
SELECT
ZNIR_CONTSIZE
INTO :TEU
FROM CONTAINERTYPES
WHERE CONTAINERTYPES.CONTAINERTYPE = :CONTYPE ;
/***************************************************/
/************ FIRST STEP CHECK FOR SPECIAL PRICE FOR THE CUSTOMER**/
:SPCPRICE = 0.00 ;
:SPCCODE  = '';
SELECT
ZYUV_CUSTSPC.PRICE,
CURRENCIES.CODE
INTO :SPCPRICE,:SPCCODE
FROM CURRENCIES,ZYUV_CUSTSPC,PART,PORTS,PORTS PORTS1,CONTAINERTYPES
WHERE ZYUV_CUSTSPC.CUST = :CUST
AND ZYUV_CUSTSPC.CONTAINERTYPE = CONTAINERTYPES.CONTAINERTYPE
AND CONTAINERTYPES.CONTAINERTYPE = :CONTYPE
AND PORTS.PORT = ZYUV_CUSTSPC.PORT
AND PORTS1.PORT = ZYUV_CUSTSPC.TOPORT
AND PORTS.PORTNAME = :LOADPORT
AND PORTS1.PORTNAME = :DESTPORT
AND :LOADDATE BETWEEN ZYUV_CUSTSPC.FROMDATE
AND ZYUV_CUSTSPC.TODATE
AND PART.PART = ZYUV_CUSTSPC.PART
AND PART.PART = :PART ;
GOTO 50 WHERE :SPCPRICE <> 0.00 ;
/************************************************/
/*** FIRST STEP GET GENERAL FREIGHT PRICE **/
:GENPRICE = 0.00 ;
:GENCODE = '' ;
SELECT
ZTAN_SPARTPRICEADD.PRICE,
CURRENCIES.CODE
INTO :GENPRICE,:GENCODE
FROM ZTAN_SPARTPRICEADD,PORTS ? ,PORTS PORTS1
?,CURRENCIES,SPARTPRICE,SUPPRICELIST,ZLIS_SPRICETYPE
WHERE PORTS.PORT = ZTAN_SPARTPRICEADD.PORT
AND PORTS1.PORT  = ZTAN_SPARTPRICEADD.TOPORT
AND ZTAN_SPARTPRICEADD.CURRENCY = CURRENCIES.CURRENCY
AND SPARTPRICE.SUPPLIST = SUPPRICELIST.SUPPLIST
AND ZTAN_SPARTPRICEADD.SUPPLIST = SUPPRICELIST.SUPPLIST
AND ZLIS_SPRICETYPE.ZLIS_SPRICETYPE = SUPPRICELIST.ZLIS_SPRICETYPE
AND ZLIS_SPRICETYPE.GENERAL = 'Y'
AND ZTAN_SPARTPRICEADD.CONTAINERTYPE = :CONTYPE
AND :LOADDATE BETWEEN ZTAN_SPARTPRICEADD.FROMDATE AND
ZTAN_SPARTPRICEADD.TILLDATE
AND ZTAN_SPARTPRICEADD.PART = SPARTPRICE.PART
AND SPARTPRICE.PART = :PART
AND PORTS.PORTNAME = :LOADPORT
AND PORTS1.PORTNAME = :DESTPORT ;
:GENPRICE = (:TEU_FLAG <> 'Y' ? :GENPRICE : :GENPRICE * :TEU) ;
/** SECOND STEP GET SURCHARGE PRICE *******/
:SURPRICE = 0.00 ;
:SURCODE = '' ;
SELECT
ZTAN_SPARTPRICEADD.PRICE,
CURRENCIES.CODE
INTO :SURPRICE,:SURCODE
FROM
ZTAN_SPARTPRICEADD,CURRENCIES,SPARTPRICE,SUPPRICELIST,
ZLIS_SPRICETYPE
WHERE   :DESTPORTID = (ZTAN_SPARTPRICEADD.PORT> 0 ?
ZTAN_SPARTPRICEADD.PORT : :DESTPORTID)
AND :LOADPORTID = (ZTAN_SPARTPRICEADD.TOPORT > 0 ?
ZTAN_SPARTPRICEADD.TOPORT : :LOADPORTID)
AND ZTAN_SPARTPRICEADD.CURRENCY = CURRENCIES.CURRENCY
AND SPARTPRICE.SUPPLIST = SUPPRICELIST.SUPPLIST
AND ZTAN_SPARTPRICEADD.SUPPLIST = SUPPRICELIST.SUPPLIST
AND ZLIS_SPRICETYPE.ZLIS_SPRICETYPE = SUPPRICELIST.ZLIS_SPRICETYPE
AND ZLIS_SPRICETYPE.SURCHARGE = 'Y'
AND ZTAN_SPARTPRICEADD.CONTAINERTYPE = :CONTYPE
AND :LOADDATE BETWEEN ZTAN_SPARTPRICEADD.FROMDATE AND
ZTAN_SPARTPRICEADD.TILLDATE
AND ZTAN_SPARTPRICEADD.PART = SPARTPRICE.PART
AND SPARTPRICE.PART = :PART  ;
:SURPRICE = (:TEU_FLAG <> 'Y' ? :SURPRICE : :SURPRICE * :TEU) ;
/**************** INSERT ITEMS TO GENERALLOAD***********/
LABEL 50 ;
/*********************************/
:LINE = 0 ;
SELECT MAX(LINE) INTO :LINE FROM GENERALLOAD ;
INSERT INTO GENERALLOAD
(LINE,RECORDTYPE,INT1,TEXT1,INT2,REAL1,TEXT2)
VALUES (:LINE + 1, '2', :ORDI,:PARTNAME,INTQUANT(:CONTCOUNT + 0.00),
(:GENPRICE <> 0 ? :GENPRICE : (:SURPRICE <> 0 ? :SURPRICE :
(:SPCPRICE <> 0.00 ? :SPCPRICE : 0))),
(:GENCODE <> '' ? :GENCODE : (:SURCODE <> '' ? :SURCODE :
(:SPCCODE <> '' ? :SPCCODE : '')))) ;
LOOP 10 ;
LABEL 80 ;
CLOSE @ZYUV_TARRIF;
LABEL 90 ;
/*********************************************************/
:CONTCOUNT = 0 ;
SELECT
COUNT(*)
INTO :CONTCOUNT
FROM ORDERS,SPLITCOSTCENTERS,COSTCENTERS,CONTAINERTYPES
WHERE ORDERS.ORD = :ORD
AND ORDERS.ORD = SPLITCOSTCENTERS.IV
AND SPLITCOSTCENTERS.TYPE = 'O'
AND SPLITCOSTCENTERS.KLINE = -1
AND SPLITCOSTCENTERS.COSTC = COSTCENTERS.COSTC
AND CONTAINERTYPES.CONTAINERTYPE = COSTCENTERS.ZYUV_CONTTYPE
AND COSTCENTERS.COSTC <>0  ;
:LINE = 0 ;
SELECT MAX(LINE) INTO :LINE FROM GENERALLOAD ;
/**** GOTO 1000 WHERE THERES SEPCIAL LOCAL PRICE FOR CUST**/
GOTO 1000 WHERE EXISTS(
SELECT
'X'
FROM ZYUV_CUSTSPC,PART
WHERE ZYUV_CUSTSPC.CUST = :CUST
AND ZYUV_CUSTSPC.PART = PART.PART
AND PART.ZYUV_LOCAL = 'Y' ) ;
/***************************************/
INSERT INTO GENERALLOAD
(LINE,RECORDTYPE,INT1,TEXT1,REAL1,TEXT2,INT2,TEXT3)
SELECT
SQL.LINE + :LINE,
'2',
0,
PART.PARTNAME,
SPARTPRICE.PRICE,
CURRENCIES.CODE,
(SPARTPRICE.ZTAN_NOBURDEN <> 'Y' ?
INTQUANT(:ZYUV_CONTCOUNT + 0.00) : INTQUANT(1.0)),
'002'
FROM
CURRENCIES,SPARTPRICE,SUPPRICELIST,ZLIS_SPRICETYPE,PART,
IMPTERMS,ORDERITEMS ?
WHERE SPARTPRICE.SUPPLIST = SUPPRICELIST.SUPPLIST
AND ZLIS_SPRICETYPE.ZLIS_SPRICETYPE = SUPPRICELIST.ZLIS_SPRICETYPE
AND IMPTERMS.IMPTERM = SUPPRICELIST.ZYUV_IMPTERM
AND IMPTERMS.IMPTERMNAME = :INCOTERMS
AND ZLIS_SPRICETYPE.LOCAL = 'Y'
AND ORDERITEMS.PART = PART.PART
AND ORDERITEMS.ORD = :ORD
AND SPARTPRICE.PART = PART.PART
AND CURRENCIES.CURRENCY = SPARTPRICE.CURRENCY ;
GOTO 2000 ;
/*************/
LABEL 1000 ;
INSERT INTO GENERALLOAD
(LINE,RECORDTYPE,INT1,TEXT1,REAL1,TEXT2,INT2,TEXT3)
SELECT
SQL.LINE + :LINE,
'2',
0,
PART.PARTNAME,
ZYUV_CUSTSPC.PRICE,
CURRENCIES.CODE,
(PART.ZTAN_NOBURDEN <> 'Y' ? INTQUANT(:ZYUV_CONTCOUNT + 0.00) :
INTQUANT(1.0)),
'002'
FROM ZYUV_CUSTSPC,CURRENCIES,PART,ORDERITEMS ?
WHERE PART.PART = ZYUV_CUSTSPC.PART
AND CURRENCIES.CURRENCY = ZYUV_CUSTSPC.CURRENCY
AND PART.ZYUV_LOCAL = 'Y'
AND ORDERITEMS.PART = PART.PART
AND ORDERITEMS.ORD = :ORD
AND ZYUV_CUSTSPC.CUST = :CUST ;
/**/
LABEL 2000 ;
/************GET FIX PRICES **/
DECLARE  @ZYUV_FIX CURSOR FOR
SELECT DISTINCT
CONTAINERTYPES.CONTAINERTYPE,
CONTAINERTYPES.CONTTYPECODE
FROM
ORDERS,CONTAINERTYPES,SPLITCOSTCENTERS,COSTCENTERS
WHERE SPLITCOSTCENTERS.IV = ORDERS.ORD
AND SPLITCOSTCENTERS.COSTC = COSTCENTERS.COSTC
AND SPLITCOSTCENTERS.TYPE = 'O'
AND SPLITCOSTCENTERS.KLINE = -1
AND COSTCENTERS.ZYUV_CONTTYPE = CONTAINERTYPES.CONTAINERTYPE
AND ORDERS.ORD = :ORD ;
OPEN @ZYUV_FIX ;
GOTO 190 WHERE :RETVAL <= 0 ;
LABEL 110 ;
:ZYUV_CONTID = 0 ;
:ZYUV_CONTCODE = '';
FETCH @ZYUV_FIX  INTO :ZYUV_CONTID,:ZYUV_CONTCODE ;
GOTO 180 WHERE :RETVAL <= 0 ;
:CONTCOUNT = 0 ;
SELECT
COUNT(*)
INTO :CONTCOUNT
FROM ORDERS,SPLITCOSTCENTERS,COSTCENTERS,CONTAINERTYPES
WHERE ORDERS.ORD = :ORD
AND ORDERS.ORD = SPLITCOSTCENTERS.IV
AND SPLITCOSTCENTERS.TYPE = 'O'
AND SPLITCOSTCENTERS.KLINE = -1
AND SPLITCOSTCENTERS.COSTC = COSTCENTERS.COSTC
AND CONTAINERTYPES.CONTAINERTYPE = COSTCENTERS.ZYUV_CONTTYPE
AND COSTCENTERS.COSTC <>0
AND CONTAINERTYPES.CONTAINERTYPE= :ZYUV_CONTID ;
/**/
:LINE  = 0 ;
SELECT MAX(LINE) INTO :LINE FROM GENERALLOAD ;
INSERT INTO GENERALLOAD (LINE,RECORDTYPE,INT1,TEXT1,
REAL1,TEXT2,INT2,TEXT3)
SELECT
SQL.LINE + :LINE,
'2',
0,
PART.PARTNAME,
SPARTPRICE.PRICE,
CURRENCIES.CODE,
(PART.ZTAN_NOBURDEN <> 'Y' ? INTQUANT(:CONTCOUNT + 0.00) :
INTQUANT(1.0)),
'002'
FROM PART,SPARTPRICE,SUPPRICELIST,CURRENCIES,CONTAINERTYPES,
ORDERITEMS ?
WHERE SUPPRICELIST.ZYUV_ALLORD = 'Y'
AND SPARTPRICE.SUPPLIST = SUPPRICELIST.SUPPLIST
AND PART.PART = SPARTPRICE.PART
AND ORDERITEMS.PART = PART.PART
AND ORDERITEMS.ORD = :ORD
AND CURRENCIES.CURRENCY = SPARTPRICE.CURRENCY
AND CONTAINERTYPES.CONTAINERTYPE = SPARTPRICE.ZTAN_CONTAINERTYPE
AND CONTAINERTYPES.CONTAINERTYPE = :ZYUV_CONTID ;
LOOP 110 ;
LABEL 180 ;
CLOSE @ZYUV_FIX ;
LABEL 190 ;
/*** ADD RATES FOR REEFER***/
:ZYUV_REEFER = 0; 
SELECT
COUNT(*) INTO 
:ZYUV_REEFER
FROM SPLITCOSTCENTERS,COSTCENTERS
WHERE SPLITCOSTCENTERS.IV = :ORD
AND SPLITCOSTCENTERS.TYPE = 'O'
AND SPLITCOSTCENTERS.KLINE = -1
AND COSTCENTERS.COSTC <>0
AND SPLITCOSTCENTERS.COSTC = COSTCENTERS.COSTC
AND ZYUV_CONTTYPE  = 5 ; 
/**/
GOTO 2000 WHERE :ZYUV_REEFER = 0 ;
/**/
:LINE  = 0 ;
SELECT MAX(LINE) INTO :LINE FROM GENERALLOAD ;
INSERT INTO GENERALLOAD (LINE,RECORDTYPE,INT1,TEXT1,
REAL1,TEXT2,INT2,TEXT3)
SELECT
SQL.LINE + :LINE,
'2',
PART.PART,
SPARTPRICE.PRICE,
CURRENCIES.CODE,
(PART.ZTAN_NOBURDEN <> 'Y' ? INTQUANT(:ZYUV_REEFER + 0.00) :
INTQUANT(1.0)),
'002'
FROM PART,SPARTPRICE,SUPPRICELIST,CURRENCIES
WHERE SUPPRICELIST.SUPPLIST = SPARTPRICE.SUPPLIST
AND PART.PART = SPARTPRICE.PART
AND CURRENCIES.CURRENCY = SPARTPRICE.CURRENCY
AND SUPPRICELIST.SUPPLIST = 16; 

LABEL 2000 ; 
EXECUTE INTERFACE 'ZYUV_PACKOTARIF',SQL.TMPFILE,'-L',:ZYUV_GEN ;
DELETE FROM GENERALLOAD ORIG ;
INSERT INTO GENERALLOAD ORIG
SELECT * FROM GENERALLOAD ;
UNLINK GENERALLOAD ;
LABEL 9988 ;
