UPDATE COSTCENTERS SET ZTAN_CONTCLOESD = 'N'
WHERE EXISTS(
SELECT
'X'
FROM SPLITCOSTCENTERS,ORDERS,ZTAN_ORDSHIP
WHERE SPLITCOSTCENTERS.COSTC = COSTCENTERS.COSTC
AND ORDERS.ORD = SPLITCOSTCENTERS.IV
AND SPLITCOSTCENTERS.KLINE = -1
AND SPLITCOSTCENTERS.TYPE ='O'
AND ZTAN_ORDSHIP.ORD = ORDERS.ORD
AND ZTAN_ORDSHIP.SHIP > 32) ; 