DECLARE ZYUV_DEM CURSOR FOR
SELECT
COSTCENTERS.COSTC,
COSTCENTERS.COSTCNAME
FROM COSTCENTERS
WHERE NIRW_CONTNO <> '' ; 
OPEC ZYUV_DEM ; 
GOTO 90 WHERE :RETVAL <= 0 ; 
LABEL 10 ;
:COSTC = 0 ;
:COSTNAME = ''; 
FETCH ZYUV_DEM INTO :COST,:COSTCNAME ; 
GOTO 80 WHERE :RETVAL <= 0 ; 
:ZYUV_DFDATE = 01/01/88 ;
SELECT
ZARI_CONTTRACK.FROMDATE
INTO :ZYUV_DFDATE
FROM ZARI_CONTTRACK,COSTCENTERS,ZTAN_CONTTRACKTYPE
WHERE ZARI_CONTTRACK.COSTC = COSTCENTERS.COSTC
AND ZTAN_CONTTRACKTYPE.CONTTRACKTYPE = ZARI_CONTTRACK.CONTTRACKTYPE
AND COSTCENTERS.COSTC = :COSTC
AND ZTAN_CONTTRACKTYPE.DF = 'Y'
ORDER BY 1 ASC ;
/***********/
:ZYUV_REDATE = 01/01/88 ;
SELECT
ZARI_CONTTRACK.FROMDATE
INTO :ZYUV_REDATE
FROM ZARI_CONTTRACK,ZTAN_CONTTRACKTYPE
WHERE ZARI_CONTTRACK.COSTC = :COSTC
AND ZARI_CONTTRACK.CONTTRACKTYPE = ZTAN_CONTTRACKTYPE.CONTTRACKTYPE
AND ZTAN_CONTTRACKTYPE.RE = 'Y'
AND ZARI_CONTTRACK.FROMDATE <> 01/01/88
ORDER BY 1 ASC ;
INSERT INTO ZYUV_CONTDEM (COSTC,KLINE,DFDATE,REDATE)
VALUES (:COSTC,1,:ZYUV_DFDATE,:ZYUV_REDATE) ; 
UPDATE ZYUV_CONTDEM SET DFDATE = :ZYUV_DFDATE,
REDATE = :ZYUV_REDATE
WHERE COSTC =  :COSTC
AND KLINE = 1 ; 
LOOP 10 ;
LABEL 80 ; 
CLOSE ZYUV_DEM ; 
LABEL 90 ; 